project_name: "seismic_walking_classification"
data_dir: "data"
data_split: 0.8
window:
  size: 512       # Number of samples per segment window
  stride: 256     # Step size between windows (allows overlap)

model:
  type: "TCN"          # Choose "TCN" or "RCNN"
  num_inputs: 1        # Single voltage channel.
  #For TCN
  num_channels: [16, 32, 64]   # Number of channels for each convolutional block.    
  dilation_base: 1.5
  # For RCNN:
  conv_channels: 16     # Number of channels for the initial convolution.
  kernel_size: 3
  dropout: 0.2
  rnn_hidden_size: 64
  num_rnn_layers: 1
  num_classes: 10       # For example: 10 persons

training:
  batch_size: 64
  lr: 0.001
  epochs: 20

wandb:                    
  api_key: "local-c667f1bae2f19ee022f2dbe2107db91a1865b96a"
  project: "bitirme_time_series"
  host: http://192.168.21.122:8000//
  entity: ""  # Optional: your username or team name on wandb
  note: "This run is for testing time series TCN model."