_wandb:
    value:
        cli_version: 0.19.6
        code_path: code/train.py
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
data_dir:
    value: data
data_split:
    value: 0.8
model:
    value:
        conv_channels: 16
        dropout: 0.2
        kernel_size: 3
        num_channels:
            - 16
            - 32
            - 64
        num_classes: 10
        num_inputs: 1
        num_rnn_layers: 1
        rnn_hidden_size: 64
        type: TCN
project_name:
    value: seismic_walking_classification
training:
    value:
        batch_size: 4096
        epochs: 20
        lr: 0.001
wandb:
    value:
        api_key: local-c667f1bae2f19ee022f2dbe2107db91a1865b96a
        entity: ""
        host: http://192.168.21.122:8000//
        note: This run is for testing time series TCN model.
        project: bitirme_time_series
window:
    value:
        size: 256
        stride: 128
